//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xylia.Match.Properties.Resx {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Progrm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Progrm() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xylia.Match.Properties.Resx.Progrm", typeof(Progrm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Game&gt;
        ///      &lt;!-- 手动添加名称缺失道具，仅ID与Alias项会被读取。--&gt;
        ///      &lt;General ID=&quot;100&quot; Alias=&quot;Test_N-ShopAccountShippingItem&quot; Name2=&quot;N-Shop帐号配送物品&quot; /&gt;
        ///      &lt;General ID=&quot;101&quot; Alias=&quot;Test_N-ShopCharacterShippingItem&quot; Name2=&quot;N-Shop角色配送物品&quot; /&gt;
        ///      &lt;General ID=&quot;1338&quot; Alias=&quot;BabaB2_0146&quot; Name2=&quot;哈迪斯（NPC武器）&quot; /&gt;
        ///      &lt;General ID=&quot;1339&quot; Alias=&quot;BabaC_0147&quot; Name2=&quot;哈迪斯（NPC武器）&quot; /&gt;
        ///      &lt;General ID=&quot;1340&quot; Alias=&quot;InsectTribeGrasshopperA_0148&quot; Name2=&quot;哈迪斯（NPC武器）&quot; /&gt;
        ///      &lt;General ID=&quot;1341 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string Game {
            get {
                return ResourceManager.GetString("Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Repack {
            get {
                object obj = ResourceManager.GetObject("Repack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Replace {
            get {
                object obj = ResourceManager.GetObject("Replace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 注意事项：
        ///1.若开始后仅输出几行就卡住，请重启程序；
        ///2.chv为存储格式，匹配中会自动导出新文件；
        ///3.由于中文编码问题，临时文件可能会发生乱码。
        ///
        ///因游戏数据量庞大，扫描会占用较多内存与CPU。
        ///
        ///读取过程中尽量退出其他进程。 的本地化字符串。
        /// </summary>
        public static string Tip_Help {
            get {
                return ResourceManager.GetString("Tip_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;table release-module=&quot;LocalData&quot; release-side=&quot;client&quot; type=&quot;tips&quot; version=&quot;1.2&quot;&gt;
        ///  &lt;!-- 这是用于MainPage的提示文本 --&gt;
        ///  &lt;record Text=&quot;按住Ctrl并滚动鼠标滚轮，可以放缩输出信息框&quot;/&gt;
        ///  &lt;record Text=&quot;小知识：任务名称为红色代表无法执行&quot;/&gt; 
        ///  &lt;record Text=&quot;小知识：自身等级大于推荐等级10级时，任务将显示为灰色&quot;/&gt;
        ///  &lt;record Text=&quot;小知识：自身等级大于推荐等级20级时，任务将变为低等级任务&quot;/&gt; 
        ///  
        ///  &lt;record Text=&quot;提示信息每隔一会便会更新&quot;/&gt;
        ///  &lt;record Text=&quot;在任务查询中，双击任务名称或副本名称，可将其复制到粘贴板&quot;/&gt;
        ///
        ///
        ///  &lt;!-- Prop 模块优先显示 --&gt;
        ///  &lt;record Text=&quot;在物品预览中，首次查询将会建立内存数据，耗时约需半分钟。此后会极大加速。&quot; proweigh [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string Tips {
            get {
                return ResourceManager.GetString("Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Update24 {
            get {
                object obj = ResourceManager.GetObject("Update24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Update24_Orange {
            get {
                object obj = ResourceManager.GetObject("Update24_Orange", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Update24_Pink {
            get {
                object obj = ResourceManager.GetObject("Update24_Pink", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 2022.11
        ///1. 数据生成拆分为数据生成与汉化生成
        ///2. 红尘往事功能底层优化
        ///3. 修复输出任务列表失效问题
        ///4. 优化任务搜索功能
        ///5. 修复任务查询界面大小偶发不适配问题
        ///6. 汉化对比功能支持对生成的 TextData.xml 进行对比
        ///7. 已支持读取虚幻4数据
        ///8. 优化通过物品名称查询物品时，处理异常缓慢的问题
        ///9. 优化多派系技能加成显示
        ///10. 修复存在字体的文本在多行时无法完全显示问题
        ///
        ///
        ///
        ///2022.03.01
        ///1.框架升级至NET5.0
        ///
        ///
        ///2021.09.08
        ///1.修复汉化超出Excel工作表数量上限会报错的问题
        ///2.优化数据搜索逻辑
        ///3.优化商店进行物品筛选会卡顿很久的问题
        ///
        ///
        ///2021.07.21
        ///1.支持17.0物品结构
        ///2.支持封魔录和印章的数据结构
        ///3.支持查看双剑职业奖励
        ///4.优化解包过程逻辑
        ///
        ///
        ///2021.07.05
        ///1.稳定性优化
        ///
        ///2021.07.01
        ///1.修复商店图标导出无效的问题
        ///2.修复部分前端交互问题
        ///3.修复选择型奖励不显示可获得数量的问题
        ///4.优化聚灵阁奖励首次载入速度
        ///5 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string UpdateLog {
            get {
                return ResourceManager.GetString("UpdateLog", resourceCulture);
            }
        }
    }
}
